In [1]:
import pandas as pd

In [2]:
dados = {
    'Nome': ['Alice', 'Bob', 'Charlie'],
    'Idade': [24, 30, 22],
    'Cidade': ['São Paulo', 'Rio de Janeiro', 'Belo Horizonte']
}

In [4]:
df = pd.DataFrame(dados)
df

      Nome  Idade          Cidade
0    Alice     24       São Paulo
1      Bob     30  Rio de Janeiro
2  Charlie     22  Belo Horizonte

In [6]:
df.head(1)

    Nome  Idade     Cidade
0  Alice     24  São Paulo

In [8]:
df.tail(1)

      Nome  Idade          Cidade
2  Charlie     22  Belo Horizonte

In [10]:
dados_notas = {
    'Nome': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Matemática': [85, 90, 78, 88, 92],
    'Física': [80, 85, 88, 85, 95],
    'Química': [78, 82, 85, 80, 88]
}

In [12]:
df_notas = pd.DataFrame(dados_notas)  
df_notas

      Nome  Matemática  Física  Química
0    Alice          85      80       78
1      Bob          90      85       82
2  Charlie          78      88       85
3    David          88      85       80
4      Eva          92      95       88

In [19]:
# Calculando a média das notas de cada aluno
df_notas['Média'] = df_notas[['Matemática', 'Física', 'Química']].mean(axis=1)
df_notas

      Nome  Matemática  Física  Química      Média
0    Alice          85      80       78  81.000000
1      Bob          90      85       82  85.666667
2  Charlie          78      88       85  83.666667
3    David          88      85       80  84.333333
4      Eva          92      95       88  91.666667

In [22]:
# Identificar alunos aprovados com nota boa (média >= 82.5)
alunos_aprovados = df_notas[df_notas['Média'] >= 84.5]
alunos_aprovados

  Nome  Matemática  Física  Química      Média
1  Bob          90      85       82  85.666667
4  Eva          92      95       88  91.666667

In [24]:
# Exibir a média e os alunos aprovados
df_notas[['Nome', 'Média']]
df_notas

      Nome  Matemática  Física  Química      Média
0    Alice          85      80       78  81.000000
1      Bob          90      85       82  85.666667
2  Charlie          78      88       85  83.666667
3    David          88      85       80  84.333333
4      Eva          92      95       88  91.666667

In [25]:
alunos_aprovados[['Nome', 'Média']]
alunos_aprovados

  Nome  Matemática  Física  Química      Média
1  Bob          90      85       82  85.666667
4  Eva          92      95       88  91.666667